### ISSUE TITLE
after a few opens the script crash "The provided token seems to be invalid."

### ISSUE THREAD

**Issue by TheLinuxChoice5** [Tenclea/Discord-Loobox-Opener#1]
![carsh](https://github.com/Tenclea/Discord-Loobox-Opener/assets/125088134/5d933266-739e-4b09-972f-fda663c4f377)

**Comment by Tenclea** [comment]
Did you use the script or compiled version ?

**Comment by TheLinuxChoice5** [comment]
script on windows, but i tested on linux and there is not an issue so idk

**Comment by Tenclea** [comment]
Might have been connexion issues ? I'll try to update the script if anyone else has similar issues

**Comment by TheLinuxChoice5** [comment]
0% chance connection issue 1gb/s up nd down

**Comment by Tenclea** [comment]
please let me know if it happens again
